### ISSUE TITLE
Implement data type enum

### ISSUE THREAD

**Issue by andygrove** [andygrove/rdbc#7]
We need an enum describing all available/supported data types. It could be based on https://docs.oracle.com/javase/8/docs/api/java/sql/JDBCType.html

**Comment by KenSuenobu** [comment]
Are you wanting an enum that just defines the sizes, or do you want an enum that contains a store of sorts for each result?

**Comment by rumatoest** [comment]
Should consider that JDBC lack of some features like supporting JSON like column types. And it is also not so good for working with array types.

**Comment by andygrove** [comment]
Closing this for now since there is a basic enum in place.

```rust
/// RDBC Data Types
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum DataType {
    Bool,
    Byte,
    Char,
    Short,
    Integer,
    Float,
    Double,
    Decimal,
    Date,
    Time,
    Datetime,
    Utf8,
    Binary,
}
```
